DELETE FROM marketplaces WHERE flavor in
('Zarafa', 'OwnCloud', 'WordPress', 'Moodle', 'PrestaShop',
 'Ghost','Discourse','Redmine','VestaCP','Ajenti',
 'Java','Rails','PHP', 'Play','Nodejs','CCPlus','Python',
 'DockerContainer', 'Hadoop', 'Spark', 'SparkNotebook',
 'DreamFactory','Pimcore','Jenkins','eXo Platform', 'Jenkins', 'Mautic', 'ProcessMaker Open Source Edition','MediaWiki','Gitlab','OwnCloud');
