#!/bin/bash
set -e

MEGAM_HOME=/var/lib/megam

mkdir -p $MEGAM_HOME/megamgateway
cp  /usr/share/megam/megamgateway/conf/marketplaces.yaml $MEGAM_HOME/megamgateway/
cp  /usr/share/megam/megamgateway/conf/gateway.conf  $MEGAM_HOME/megamgateway/
cp  /usr/share/megam/megamgateway/conf/logger.xml  $MEGAM_HOME/megamgateway/

[ -d /var/run/megamgateway ] && rm -rf /var/run/megamgateway

echo "installed."
