#!/bin/sh

if [ -d "/usr/share/detio/virtenginegateway" ]; then
  rm -r /usr/share/detio/virtenginegateway
fi

if [ -d "/var/lib/detio/virtenginegateway" ]; then
  rm -r /var/lib/detio/virtenginegateway
fi

if [ -d "/var/log/detio/virtenginegateway" ]; then
  rm -r /var/log/detio/virtenginegateway
fi


if [ -d "/var/run/detio/virtenginegateway" ]; then
  rm -r /var/run/detio/virtenginegateway
fi
