#!/bin/bash
[ -d /var/lib/megam/verticegateway]   || mkdir  -p /var/lib/megam/verticegateway/
[ -d /var/run/megam/verticegateway/ ] ||  mkdir -p /var/run/megam/verticegateway/
[ -d /var/log/megam/verticegateway/ ] ||  mkdir -p /var/log/megam/verticegateway/
