#!/bin/bash
[ -d /var/lib/megam/megamgateway]   || mkdir  -p /var/lib/megam/megamgateway/
[ -d /var/run/megam/megamgateway/ ] ||  mkdir -p /var/run/megam/megamgateway/
[ -d /var/log/megam/megamgateway/ ] ||  mkdir -p /var/log/megam/megamgateway/
