#!/bin/bash
set -e

MEGAM_HOME=/var/lib/megam
MEGAM_USER=megam

mkdir -p $MEGAM_HOME/verticegateway
cp  /usr/share/megam/verticegateway/conf/base.cql $MEGAM_HOME/verticegateway/base.cql
cp  /usr/share/megam/verticegateway/conf/gateway.conf  $MEGAM_HOME/verticegateway/gateway.conf
cp  /usr/share/megam/verticegateway/conf/logger.xml  $MEGAM_HOME/verticegateway/
cp  /usr/share/megam/verticegateway/conf/VERSION /usr/share/megam/verticegateway/

dist=`grep PRETTY_NAME /etc/*-release | awk -F '="' '{print $2}'`
os=$(echo $dist | awk '{print $1;}')
id=`grep VERSION_ID /etc/*-release | awk -F '="' '{print $2}'`
version=$(echo $id | awk '{print $1;}')
versionId=${version::-1}
if [ "$os" == "Ubuntu" ] &&  [ "$versionId" == "14.04" ]; then
  echo $os "verticegateway 1.5"
else if [ "$os" == "Ubuntu" ] &&  [ "$versionId" == "16.04" ] || [ "$os" == "Debian" ]; then
cat > /etc/systemd/system/verticegateway.service <<EOF
## Systemd script that starts vertice gateway
[Unit]
Description=Vertice Gateway
After=network.target
After=runlevel2.target
After=runlevel3.target
After=runlevel4.target
After=runlevel5.target
[Service]
ExecStart=/usr/share/megam/verticegateway/bin/verticegateway -Dlogger.file=/var/lib/megam/verticegateway/logger.xml -Dconfig.file=/var/lib/megam/verticegateway/gateway.conf
KillMode=mixed
EOF
rm /etc/init/verticegateway.conf

else
   echo "Unsupported Linux OS"
fi
fi

if [ "$1" = "configure" ]; then
    if ! dpkg-statoverride --list /var/log/megam >/dev/null 2>&1; then
         dpkg-statoverride --update --add $MEGAM_USER root 755 /var/log/megam
    fi
fi

#initctl reload-configuration
echo "verticegateway not yet started. Try manually 'systemctl start verticegateway or start verticegateway'"
