#!/bin/sh

if [ -d "/usr/share/megam/virtenginegateway" ]; then
  rm -r /usr/share/megam/virtenginegateway
fi

if [ -d "/var/lib/megam/virtenginegateway" ]; then
  rm -r /var/lib/megam/virtenginegateway
fi

if [ -d "/var/log/megam/virtenginegateway" ]; then
  rm -r /var/log/megam/virtenginegateway
fi


if [ -d "/var/run/megam/virtenginegateway" ]; then
  rm -r /var/run/megam/virtenginegateway
fi
