#!/bin/bash
[ -d /var/log/detio/virtenginegateway/ ] ||  mkdir -p /var/log/detio/virtenginegateway/

[ -d /var/lib/detio/virtenginegateway/ ] ||  mkdir -p /var/lib/detio/virtenginegateway/

[ -d /var/run/detio ] || mkdir /var/run/detio
