#!/bin/bash
[ -d /var/log/megam/virtenginegateway/ ] ||  mkdir -p /var/log/megam/virtenginegateway/

[ -d /var/lib/megam/virtenginegateway/ ] ||  mkdir -p /var/lib/megam/virtenginegateway/

[ -d /var/run/megam ] || mkdir /var/run/megam
