#!/bin/bash
[ -d /var/log/megam/verticegateway/ ] ||  mkdir -p /var/log/megam/verticegateway/

[ -d /var/lib/megam/megamgateway/ ] ||  mkdir -p /var/lib/megam/megamgateway/

[ -d /var/run/megam ] || mkdir /var/run/megam
